ALTER TABLE products
ADD COLUMN type VARCHAR(20);

UPDATE products
SET type = 'ONLINE_CONTENT'
WHERE category IN ('VIRTUAL_MODEL', 'MUSIC');

UPDATE products
SET type = 'OFFLINE_CONTENT'
WHERE type IS NULL;

ALTER TABLE products
MODIFY COLUMN type VARCHAR(20) NOT NULL;
